name: R CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/r-ci.yml'
      - 'NAMESPACE'
      - 'R/**'
      - 'man/**'
      - 'tests/**'
      - 'vignettes/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/r-ci.yml'
      - 'NAMESPACE'
      - 'R/**'
      - 'man/**'
      - 'tests/**'
      - 'vignettes/**'

permissions:
  contents: read

concurrency:
  group: r-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  r-cmd-check:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
          extra-repositories: https://rtemis-org.r-universe.dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          cache-version: 1

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual", "--compact-vignettes=gs+qpdf")'
